### PR TITLE
merge_db_analyze_type_annotate

### PR DESCRIPTION
**Pull request by technicalgrp89**
merge_db_analyze_type_annotate
data type signatures are added for all defined functions of analyze_parse_db.py

### CODE REVIEW

**Comment by technicalgrp89** [comment]
@cderb , @alexandraBara , @JehandadKhan , Let me know for the review comments.

**Comment by JehandadKhan** [comment]
@technicalgrp89  Please add the typecheck command for the annotated file to the Jenkins file as we discussed.

**Review by cderb — APPROVED** [review]
lgtm

**Comment by technicalgrp89** [comment]
@JehandadKhan @cderb @alexandraBara CI check is passing. I have added , mypy check commond in the pylint stage. Let me know.

**Review by alexandraBara — APPROVED** [review]

**Pull request merged**
