### PR TITLE
pytestSuite1-merge db & utils tests added

### PR DESCRIPTION
**Pull request by technicalgrp89**
/vars/utils.groovy/pytestSuite1()
    test_utils.py
    test_merge_db_functions.py
tests are added.

### CODE REVIEW

**Comment by technicalgrp89** [comment]
@cderb @alexandraBara @JehandadKhan review needed. As of noe CI check is failing , b'se changes/Pull Req under review.

**Comment by JehandadKhan** [comment]
@technicalgrp89 Seems like the CI is failing, also please update the converage percentage in the repo

**Review by alexandraBara — CHANGES_REQUESTED** [review]
@technicalgrp89  did you mean to make these changes to this PR? https://github.com/ROCmSoftwarePlatform/MITuna/pull/815/files
The above PR is where the test_merge_db_function utest is added but its not added to the groovy file like you do here.

**Comment by technicalgrp89** [comment]
> @technicalgrp89 did you mean to make these changes to this PR? https://github.com/ROCmSoftwarePlatform/MITuna/pull/815/files The above PR is where the test_merge_db_function utest is added but its not added to the groovy file like you do here.

@alexandraBara it is added under pytest suite1.

**Comment by technicalgrp89** [comment]
utils.groovy file changes are pushed into Following PR's - #804 and #815

**Pull request closed without merging**
