### PR TITLE
updated python and numpy versions

### PR DESCRIPTION
**Pull request by msaudulhassan**

### CODE REVIEW

**Comment by alexandraBara** [comment]
Its not passing the CI, lets investigate why it's failing

**Comment by msaudulhassan** [comment]
packages not found. will fix this in peace on monday :)

**Comment by msaudulhassan** [comment]
Passed the CI. 

PS: CI feels like [this](https://tenor.com/view/lord-of-the-rings-you-shall-not-pass-not-pass-gandal-the-grey-gandalf-gif-7706023)

**Review by alexandraBara — APPROVED** [review]

**Comment by JehandadKhan** [comment]
> Passed the CI.
> 
> PS: CI feels like [this](https://tenor.com/view/lord-of-the-rings-you-shall-not-pass-not-pass-gandal-the-grey-gandalf-gif-7706023)

So you are the Balrog ?

**Review by JehandadKhan — APPROVED** [review]

**Comment by msaudulhassan** [comment]
> > Passed the CI.
> > PS: CI feels like [this](https://tenor.com/view/lord-of-the-rings-you-shall-not-pass-not-pass-gandal-the-grey-gandalf-gif-7706023)
> 
> So you are the Balrog ?

The CI did treat me no better

**Pull request merged**
