### PR TITLE
Merge Dockerfiles

### PR DESCRIPTION
**Pull request by cderb**
merge dockerfiles, include base image branching in updated dockerfile

### CODE REVIEW

**Comment by cderb** [comment]
CI is blocked by errors related to perf_config_table changes, stalled until previous pr is merged.

**Comment by cderb** [comment]
Opened an issue LWPTUNA-141 for updating the ci to use new performance pipeline commands. 
Ok to proceed with PR.

**Comment by alexandraBara** [comment]
@cderb do any of our docs need updating for this?

**Comment by JehandadKhan** [comment]
@alexandraBara and @iq136boy please review the PR

**Review by JehandadKhan — APPROVED** [review]
Very nice, I like the multi-stage docker trick

**Review by alexandraBara — APPROVED** [review]

**Pull request merged**
